version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    networks:
      - microservice-net

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    networks:
      - microservice-net

order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    networks:
      - microservice-net


  gateway-service:
    build: ./gateway-service
    ports:
      - "3003:3003"
    networks:
      - microservice-net
    depends_on:
      - user-service
      - product-service

networks:
  microservice-net:
    driver: bridge
